version: "3.8"

services:
  db:
    image: postgres:16
    container_name: test-scheduler-db
    environment:
      POSTGRES_DB: test_scheduler
      POSTGRES_USER: kseni1
      POSTGRES_PASSWORD: kseni1
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: test-scheduler-app
    depends_on:
      - db
    ports:
      - "8087:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_scheduler
      SPRING_DATASOURCE_USERNAME: kseni1
      SPRING_DATASOURCE_PASSWORD: kseni1

volumes:
  db_data: