spring.application.name=testscheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/test_scheduler
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=kseni1
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true